LocalPick/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),	
    path('auth/', include("users.urls")),
    path('store/', include("stores.urls")),
    path('search/', include("search.urls")),
    path('review/', include("review.urls")),
    path('appetite/', include("appetite.urls")),
    path('like/', include("like.urls")),
    path('upload/', include("upload.urls"))
]

like/urls.py
from django.urls import path
from .apis import LikeAPI, LikeListAPI
from .views import StoreLikeListView
from . import views



app_name = 'like'

urlpatterns = [
    # {% url 'like:api' %}
    path("api/", views.likes, name="api"),
    # {% url 'like:list_api' %}
    path("api/list/", LikeListAPI.as_view(), name="list_api"),

    path("list/", StoreLikeListView.as_view(), name="list")
]

stores/urls.py
from django.urls import path
from .apis import StoreDetailAPI, StoreListAPI, StoreCreateAPI, StoreImageAPI, StorePersonalListAPI
from .views import StoreCreateView, StoreImageCreate, StoreDetailView, StoreListView


app_name = 'store'

urlpatterns = [
    # {% url 'store:detail' %}
    path("detail/<int:pk>", StoreDetailView.as_view(), name="detail"),
    # {% url 'store:detail_api' %}
    path("api/detail/<int:pk>", StoreDetailAPI.as_view(), name="detail_api"),

    # {% url 'store:list_api'%}
    path("api/list/<int:pk>", StoreListAPI.as_view(), name="list_api"),
    # {% url 'store:list' %}
    path("list/", StoreListView.as_view(), name="list"),

    # {% url 'store:create_api' %}
    path("api/create/", StoreCreateAPI.as_view(), name="create_api"),
    # {% url 'store:create_image' %}
    path("image/create/",StoreImageCreate.as_view(), name="create_image"),
    # {% url 'store:per_api_list' %}
    path("personal/api/list/", StorePersonalListAPI.as_view(), name="per_api_list"),


    path("duffufkckaRo/", StoreCreateView.as_view()),
    path("api/image/<int:pk>", StoreImageAPI.as_view(),name="image_api")
]

stores/models.py
from django.db import models
from users.models import User

# Create your models here.


class Store(models.Model):
    store_name = models.CharField(max_length=30, default = "----")
    store_time = models.TextField(blank = True)
    store_adress = models.CharField(max_length=50, default="----")
    store_tel = models.CharField(max_length=20, default="----")
    category = models.ForeignKey("Category", on_delete = models.SET_NULL, null=True, db_column='category_id')
    # like_users = models.ManyToManyField('users.User', related_name="like_users", blank=True)

    # def count_like_users(self):
    #     return self.like_users.count()
    
    def __str__(self):
        return self.store_name


class Category(models.Model):
    category_name = models.CharField(max_length=25, default = "X")
    
    def __str__(self):
        return self.category_name


class Image(models.Model):
    store = models.ForeignKey("Store", on_delete=models.CASCADE, null=True, db_column="store_id")
    image_tag = models.TextField(null=True)

stores/views.py
from django.shortcuts import render, redirect
from rest_framework.views import APIView
from .models import Category, Image
from appetite.models import Appetite
from django.views.decorators.csrf import csrf_exempt
import os
from uuid import uuid4
from LocalPick.settings import STORE_IMAGE
from rest_framework.response import Response
from .utils import user_session_authticate


# Create your views here.

class StoreCreateView(APIView):
    def get(self, request):
        category_list = Category.objects.all()
        return render(request, "store/create.html", {"category_list": category_list})


class StoreImageCreate(APIView):
    @csrf_exempt
    def post(self, request):

        store_id = request.data.get('store_id')
        image_list = request.FILES.getlist('files')

        for i in image_list:

            uuid_name = uuid4().hex
            save_path = os.path.join(STORE_IMAGE, uuid_name)
            with open(save_path, 'wb+') as destination:
                for chunk in i.chunks():
                    destination.write(chunk)

            image = uuid_name

            Image.objects.create(image_tag=image, store_id=store_id)
        return Response(status=200)


class StoreDetailView(APIView):
    def get(self, request, pk):
        info = user_session_authticate(request)
        if info is None:
            return redirect("users:login")
        # info에 url 에서 받아온 pk 담아서 넘김
        info['pk'] = pk

        return render(request, "store/detail.html", info)


class StoreListView(APIView):
    def get(self, request):
        info = user_session_authticate(request)
        if info is None:
            return redirect("users:login")
        user_id = request.session.get("_auth_user_id", None)

        taste = Appetite.objects.filter(user_id=user_id).first()



        # if taste is None:
        #     return render(request, "users/taste.html")
        # {{ user.정보 }}로 사용 ex) {{ user.nickname }}
        return render(request, "store/list.html", info)

templates/store/detail.html
{% extends 'base.html' %}

{% block content %}
    <div id="section">

    <div class="detail_top_box">
        <div class="detail_top">
            <button id="back" onclick="history.back()">
                <i class="fas fa-chevron-left fa-2x"></i>
            </button>
            <b id="store_name"></b>
        </div>
    </div>

    <div class="store">
        <div class="swiper mySwiper">
            <div id="image_slide" class="swiper-wrapper">

            </div>
            <div class="swiper-pagination"></div>
        </div>
    </div>

    <div id="store_info" class="detail"></div>

    <div class="result">
        <b id="detail_review">전체 리뷰 결과</b>
        <div class="detail_star">
            <div class="star-ratings">

                <div class="star-ratings-fill space-x-2 text-lg">
                    <span>★</span>
                </div>
                <div class="star-ratings-base space-x-2 text-lg">
                    <span>★</span><span id="avg_star"></span>
                </div>
            </div>
        </div>
        <button id="write" type="button"><i class="fas fa-pen"> 리뷰 작성하기</i></button>
    </div>

    <div class="review">
        <button id="review_btn"><b>리 뷰</b></button>
    </div>

    <div id="review_list" class="review_detail">


    </div>

    <script>
        var swiper = new Swiper(".mySwiper", {
            pagination: {
                el: ".swiper-pagination",
            },
        });

        $(function () {
            $('#heart').click(function () {
                location.href = "{% url 'like:api' %}"
            });
        });

        $('#write').click(function () {
            location.href = "{% url 'review:create' pk=pk %}";
        });


        $(document).ready(function () {
            $.ajax({
                url: "{% url 'store:detail_api' pk=pk %}",
                headers: {
                    "Authorization": "Token {{ token }}",
                },
                method: "GET",
                datatype: 'json',
                success: function (data) {
                    var info_html = ""
                    info_html += "<p><b>" + data.store_name + "</p></b>"
                    info_html += "<ul>"
                    info_html += "<li><p>" + data.store_adress + "</p></li>"
                    info_html += "<li><p>" + data.store_tel + "</p></li>"
                    info_html += "</ul>"
                    document.getElementById("store_info").innerHTML = info_html
                    $('#store_name').text(data.store_name);

                },
                error: function (request, status, error) {
                    console.log('error');
                    console.log(error);
                },
                complete: function (data) {
                    console.log('끝');
                }
            });

            $.ajax({
                url: "{% url 'store:image_api' pk=pk %}",
                headers: {
                    "Authorization": "Token {{ token }}",
                },
                method: "GET",
                datatype: 'json',
                success: function (data) {
                    var image_html = "";
                    console.log(data);
                    for (var i = 0; i < data.length; i++) {
                        image_html += "<div id='sw' class='swiper-slide'>"
                        image_html += "<img class='detail_image' src='" + data[i].image_tag + "'>"
                        image_html += "</div>"
                    }

                    document.getElementById("image_slide").innerHTML = image_html

                },
                error: function (request, status, error) {
                    console.log('error');
                    console.log(error);
                },
                complete: function (data) {
                    console.log('끝');
                }
            });

            $.ajax({
                url: "{% url 'review:list_api' pk=pk %}",
                headers: {
                    "Authorization": "Token{{ token }}",
                },
                method: "GET",
                datatype: 'json',
                success: function (review) {
                    var review_desc = "";
                    var i = 0;
                    var star_sum = 0;
                    console.log(review);
                    while (i < review.length) {
                        star_sum += review[i].star_rating;
                        review_desc += "<div class='review_box' style='display:flex; flex-direction : row;'>"
                        review_desc += "<div style='display: flex;flex-direction : column ; align-items: center; width:120px;'>"
                        review_desc += "<img style='margin-top: 5px' id='profile_review' src='/static/images/profile.png'>"
                        review_desc += "<div>"+ review[i].nickname + "</div>"
                        review_desc += "<div style='border-radius:18px; border: 1px solid white; background-color: #dddddd; padding:5px'>"
                        review_desc += "<img id='taste_img' src='/static/images/spicy.png' alt='매워'>"
                        review_desc += "<img id='taste_img' src='/static/images/salt.png' alt='짜'>"
                        review_desc += "<img id='taste_img' src='/static/images/sweet.png' alt='달아'>"
                        review_desc += "<img id='taste_img' src='/static/images/amount.png' alt='양'>"
                        review_desc += "</div></div>"
                        review_desc += "<div style='flex-direction : column;'>"
                        review_desc += "<div style='display:flex;justify-content: space-between; flex-direction: row; padding-right: 8px; padding-top: 5px'>"
                        review_desc += "<div>"
                        review_desc += "<div class='star-ratings'>"
                        review_desc += "<div class='star-ratings-fill space-x-2 text-lg'>"
                        review_desc += "<span>★</span>"
                        review_desc += "</div><div class='star-ratings-base space-x-2 text-lg'>"
                        review_desc += "<span>★</span>" + review[i].star_rating
                        review_desc += "</div></div><div> </div>"
                        review_desc += "</div> <div>"
                        review_desc += "<img id='review_img' src='/static/images/review_amount.png' alt='양'>"
                        review_desc += "<img id='review_img' src='/static/images/kindness.png' alt='친철도'>"
                        review_desc += "<img id='review_img' src='/static/images/hygiene.png' alt='위생'>"
                        review_desc += "<img id='review_img' src='/static/images/price.png' alt='가격'>"
                        review_desc += "</div></div>"
                        review_desc += "<div style='border: solid 1px #BDBDBD; height: 83px; width: 219px; border-radius: 6px; margin-top: 7px'>" + review[i].description
                        review_desc += "</div></div></div>"
                        i++;
                    }
                    var star_avg = star_sum / review.length
                    document.getElementById("review_list").innerHTML = review_desc
                    document.getElementById("avg_star").innerText = star_avg

                },
                error: function (request, status, error) {
                    alert("error");
                    console.log('error');
                    console.log(error);
                }
                ,
                complete: function (data) {
                    console.log('끝');
                }
            });
        });
    </script>
{% endblock %}

templates/store/likelist.html
{% extends 'base.html' %}

{% block content %}

    {% include 'header.html' %}

    <div class="head">
        <h2>{{ user.nickname }} 님의<br><span style="color: royalblue">좋아요</span> 맛집 리스트입니다.</h2>
    </div>

    <div class="listbox1" id="listbox1">
        <div id="like_list" class="listbox" style="flex-direction: column">

        </div>
    </div>


    <div class="local_navbar">
        <div class="n-box" id="list">
            <i class="fas fa-th fa-2x"></i>
        </div>
        <div class="n-box" id="search">
            <i class="fas fa-search fa-2x"></i>
        </div>
        <div class="n-box" id="heart">
            <i class="fas fa-heart fa-2x fc-blue"></i>
        </div>
        <div class="n-box" id="user">
            <i class="fas fa-user-circle fa-2x"></i>
        </div>
    </div>

    <script>

     function store_like(id) {
            console.log("hi")
            $.ajax({
                url: "{% url 'like:api' %}", // data를 전송할 url 입니다.
                method: "POST",
                data: {
                    'csrfmiddlewaretoken': "{{ csrf_token }}",
                    'store_id': id
                }, // post_id 라는 name으로 id 값 전송
                dataType: "json",
                success: function (response) { // ajax 통신이 정상적으로 완료되었을 때
                    if (response.is_liked) {
                        var class_cnt = document.getElementsByClassName(response.store_id).length;
                        for (var i = 0; i < class_cnt; i++){
                            document.getElementsByClassName(response.store_id)[i].classList.replace('far', 'fas');
                            document.getElementsByClassName(response.store_id)[i].style.color = "red";
                        }

                    } else {
                        var class_cnt = document.getElementsByClassName(response.store_id).length;
                        for (var i = 0; i < class_cnt; i++){
                            document.getElementsByClassName(response.store_id)[i].classList.replace('fas', 'far');
                            document.getElementsByClassName(response.store_id)[i].style.color = "royalblue";
                        }

                    }
                }
            });
        }


        $(document).ready(function () {
            $.ajax({
                url: "{% url 'like:list_api' %}",
                headers: {
                    "Authorization": "Token {{ token }}",
                },
                method: "GET",
                datatype: 'json',
                async: false,
                success: function (data) {
                    console.log(data);
                    var list = data.storeList;
                    var list_html = "";
                    for (var i = 0; i < list.length; i++) {
                        var store_id = list[i].store_id_id;
                        var is_liked = list[i].is_liked;
                        var store_name = list[i].store_name;
                        var image_tag = list[i].image_tag;
                        if(i%2 == 0){
                            list_html += "<div style='display: flex'>";
                        }
                        list_html += "<div id='box'>";
                        list_html += "<div class='photo_box'>";
                        list_html += "<div id='photo'>";
                        list_html += "<a href='/store/detail/" + store_id + "'>"
                        list_html += "<img class='list_image' src='" + image_tag + "'></a>";
                        if (is_liked == false) {
                            list_html += "<i id='" + store_id + "' onclick='store_like(this.id)' class='far fa-heart " + store_id + "' style='color: royalblue;'></i>";
                        } else if (is_liked == true) {
                            list_html += "<i id='" + store_id + "' onclick='store_like(this.id)' class='fas fa-heart " + store_id + "' style='color: red;'></i>";
                        }
                        list_html += "</div><div class='name_box'>";
                        list_html += "<a href='/store/detail/" + store_id + "'>" + store_name + "</a>";
                        list_html += "</div> </div> </div>";
                        if(i%2 == 1){
                            list_html += "</div>";
                        }
                    }
                    document.getElementById("like_list").innerHTML = list_html;
                },
                error: function (request, status, error) {
                    alert("error");
                    console.log('error');
                    console.log(error);
                },
                complete: function (data) {
                    console.log('끝');
                }
            });

        });


    </script>
{% endblock %}

templates/store/list.html
{% extends 'base.html' %}

{% block content %}
    {% include 'header.html' %}
    <div id="section">
        <div class="head">
            <h2>{{ user.nickname }} 님의<br>추천 맛집입니다.</h2>
        </div>
        <div class="first_box">
            <div class="store_list_box">
                <div class="list_name">
                    <b>{{ user.nickname }} 님 맞춤!!</b>
                </div>
                <div class="swiper mySwiper">
                    <div id="personal_slider" class="swiper-wrapper">

                    </div>
                </div>
            </div>
            <div class="store_list_box">
                <div class="list_name">
                    <b>추천 카페</b>
                </div>
                <div class="swiper mySwiper">
                    <div id="cafe_slider" class="swiper-wrapper">

                    </div>
                </div>
            </div>
            <div class="store_list_box">
                <div class="list_name">
                    <b>한식 추천</b>
                </div>
                <div class="swiper mySwiper">
                    <div id="korean_slider" class="swiper-wrapper">

                    </div>
                </div>
            </div>

        </div>
    </div>

    {% include 'navbar.html' %}

    <script>



        function store_like(id) {
            console.log("hi")
            $.ajax({
                url: "{% url 'like:api' %}", // data를 전송할 url 입니다.
                method: "POST",
                data: {
                    'csrfmiddlewaretoken': "{{ csrf_token }}",
                    'store_id': id
                }, // post_id 라는 name으로 id 값 전송
                dataType: "json",
                success: function (response) { // ajax 통신이 정상적으로 완료되었을 때
                    if (response.is_liked) {
                        var class_cnt = document.getElementsByClassName(response.store_id).length;
                        for (var i = 0; i < class_cnt; i++){
                            document.getElementsByClassName(response.store_id)[i].classList.replace('far', 'fas');
                            document.getElementsByClassName(response.store_id)[i].style.color = "red";
                        }

                    } else {
                        var class_cnt = document.getElementsByClassName(response.store_id).length;
                        for (var i = 0; i < class_cnt; i++){
                            document.getElementsByClassName(response.store_id)[i].classList.replace('fas', 'far');
                            document.getElementsByClassName(response.store_id)[i].style.color = "royalblue";
                        }

                    }
                }
            });
        }

        $(document).ready(function () {
            $.ajax({
                url: "{% url 'store:list_api' 6 %}",
                headers: {
                    "Authorization": "Token {{ token }}",
                },
                method: "GET",
                datatype: 'json',
                async: false,
                success: function (data) {
                    var list = data.storeList;
                    var list_html = "";
                    for (var i = 0; i < list.length; i++) {
                        var store_id = list[i].id;
                        var is_liked = list[i].is_liked;
                        var store_name = list[i].store_name;
                        var image_tag = list[i].image_tag;
                        list_html += "<div class='swiper-slide'>";
                        list_html += "<div class='photo_box'>";
                        list_html += "<div id='photo'>";
                        list_html += "<a href='/store/detail/" + store_id + "'>"
                        list_html += "<img class='list_image' src='" + image_tag + "'></a>";
                        if (is_liked == false) {
                            list_html += "<i id='" + store_id + "' onclick='store_like(this.id)' class='far fa-heart "+ store_id +"' style='color: royalblue;'></i>";
                        } else if (is_liked == true) {
                            list_html += "<i id='" + store_id + "' onclick='store_like(this.id)' class='fas fa-heart "+ store_id +"' style='color: red;'></i>";
                        }
                        list_html += "<div class='name_box'>";
                        list_html += "<a href='/store/detail/" + store_id + "'>" + store_name + "</a>";
                        list_html += "</div></div></div></div>";
                    }
                    document.getElementById("cafe_slider").innerHTML = list_html;
                },
                error: function (request, status, error) {
                    alert("error");
                    console.log('error');
                    console.log(error);
                },
                complete: function (data) {
                    console.log('끝');
                }
            });


            $.ajax({
                url: "{% url 'store:list_api' 1 %}",
                headers: {
                    "Authorization": "Token {{ token }}",
                },
                method: "GET",
                datatype: 'json',
                async: false,
                success: function (data) {
                    var list = data.storeList;
                    var list_html = "";

                    for (var i = 0; i < list.length; i++) {
                        var store_id = list[i].id;
                        var is_liked = list[i].is_liked;
                        var store_name = list[i].store_name;
                        var image_tag = list[i].image_tag;
                        list_html += "<div class='swiper-slide'>";
                        list_html += "<div class='photo_box'>";
                        list_html += "<div id='photo'>";
                        list_html += "<a href='/store/detail/" + store_id + "'>"
                        list_html += "<img class='list_image' src='" + image_tag + "'></a>";
                        if (is_liked == false) {
                            list_html += "<i id='" + store_id + "' onclick='store_like(this.id)' class='far fa-heart "+ store_id +"' style='color: royalblue;'></i>";
                        } else if (is_liked == true) {
                            list_html += "<i id='" + store_id + "' onclick='store_like(this.id)' class='fas fa-heart "+ store_id +"' style='color: red;'></i>";
                        }
                        list_html += "<div class='name_box'>";
                        list_html += "<a href='/store/detail/" + store_id + "'>" + store_name + "</a>";
                        list_html += "</div></div></div></div>";
                    }
                    document.getElementById("korean_slider").innerHTML = list_html;
                },
                error: function (request, status, error) {
                    alert("error");
                    console.log('error');
                    console.log(error);
                },
                complete: function (data) {
                    console.log('끝');
                }
            });


            $.ajax({
                url: "{% url 'store:per_api_list' %}",
                headers: {
                    "Authorization": "Token {{ token }}",
                },
                method: "GET",
                datatype: 'json',
                async: false,
                success: function (data) {
                    var list = data.storeList;
                    var list_html = "";

                    for (var i = 0; i < list.length; i++) {
                        var store_id = list[i].id;
                        var is_liked = list[i].is_liked;
                        console.log(is_liked);
                        var store_name = list[i].store_name;
                        var image_tag = list[i].image_tag;
                        list_html += "<div class='swiper-slide'>";
                        list_html += "<div class='photo_box'>";
                        list_html += "<div id='photo'>";
                        list_html += "<a href='/store/detail/" + store_id + "'>"
                        list_html += "<img class='list_image' src='" + image_tag + "'></a>";
                        if (is_liked == false) {
                            list_html += "<i id='" + store_id + "' onclick='store_like(this.id)' class='far fa-heart "+ store_id +"' style='color: royalblue;'></i>";
                        } else if (is_liked == true) {
                            list_html += "<i id='" + store_id + "' onclick='store_like(this.id)' class='fas fa-heart "+ store_id +"' style='color: red;'></i>";
                        }

                        list_html += "<div class='name_box'>";
                        list_html += "<a href='/store/detail/" + store_id + "'>" + store_name + "</a>";
                        list_html += "</div></div></div></div>";
                    }
                    document.getElementById("personal_slider").innerHTML = list_html;
                },
                error: function (request, status, error) {
                    alert("error");
                    console.log('error');
                    console.log(error);
                },
                complete: function (data) {
                    console.log('끝');
                }
            });


        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js"></script>
    <script>
        var swiper = new Swiper(".mySwiper", {
            slidesPerView: 2,
            spaceBetween: 30,
            freeMode: true,
            pagination: {
                el: ".swiper-pagination",
                clickable: true,
            },
        });
    </script>
{% endblock %}

templates/store/swipertest.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>로컬픽</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <link rel="stylesheet" href="/static/css/stylesheet.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <script src="{% static 'js/nav.js' %}"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"/>

    <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
    <script type="module">
        import Swiper from 'https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.esm.browser.min.js'

        const swiper = new Swiper(...)
    </script>
</head>

<!-- Demo styles -->
<style>
    .swiper-slide {
        text-align: center;
        background: white;

        border: 1px solid white;
        border-radius: 5px;
        margin: 5px 15px 5px 5px;
        height: 135px;
        padding: 20px;
        box-shadow: 10px 5px 10px 5px #F5F5F5;

        /* Center slide text vertically */
        display: -webkit-box;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        -webkit-justify-content: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        -webkit-align-items: center;
        align-items: center;
    }

    .swiper-slide img {
        display: block;
        width: 100%;
        height: 100%;
        object-fit: cover;
    }

    #photo {
        border: 1px solid black;
        border-radius: 6px;
        height: 90px;
        width: 100%;
        margin-bottom: 25px;
    }

    #photo > i {
        float: right;
        margin-top: 10px;
        margin-right: 10px;
    }

    a {

    }

</style>
</head>

<body>
<div class="top_box">
    <div class="top">
        <img id="logo" src="/static/images/IMG_4613.png" alt="로컬픽">
    </div>
</div>

<div class="head">
    <h2>{{ user.nickname }} 님의<br>추천 맛집입니다.</h2>
</div>

<div class="first_box">
    <div class="list_name">
        <b>{{ user.nickname }}님 맛춤 맛집</b>
    </div>

</div>
<!-- Swiper -->
<div class="swiper mySwiper">
    <div class="swiper-wrapper">
        <div class="swiper-slide">
            <div id='photo'>
                <i class='far fa-heart'></i>
                <a href='/store/detail/" + store_id + "'>"+ list[i].store_name +"</a>
            </div>

        </div>

        <div class="swiper-slide"></div>
        <div class="swiper-slide"></div>
        <div class="swiper-slide"></div>
        <div class="swiper-slide"></div>
        <div class="swiper-slide"></div>
    </div>
    <div class="swiper-pagination"></div>
</div>

<div class="navbar">
    <div class="n-box" id="list">
        <i class="fas fa-th fa-2x fc-blue"></i>
    </div>
    <div class="n-box" id="search">
        <i class="fas fa-search fa-2x"></i>
    </div>
    <div class="n-box" id="heart">
        <i class="fas fa-heart fa-2x"></i>
    </div>
    <div class="n-box" id="user">
        <i class="fas fa-user-circle fa-2x"></i>
    </div>
</div>

<!-- Swiper JS -->
<script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js"></script>

<!-- Initialize Swiper -->
<script>
    var swiper = new Swiper(".mySwiper", {
        slidesPerView: 2,
        spaceBetween: 30,
        freeMode: true,
        pagination: {
            el: ".swiper-pagination",
            clickable: true,
        },
    });
</script>
</body>
</html>